### ISSUE TITLE
slider and main.tpl

### ISSUE THREAD

**Issue by NYCTO1337** [viadevelop/freeweb#1] opened 2021-09-23 12:53 UTC
i changed main.php file in engine but template doesn't work fully. check screen. also doesn't work navigation buttons on main page.
![Untitled](https://user-images.githubusercontent.com/91264605/134510031-f0318318-5bca-4d65-ab5f-50e420b6d049.png)

**Comment by somnambul1st** [comment] 2021-09-23 13:42
Hello. What version of DLE did you install the template on and how did you do it?

**Comment by NYCTO1337** [comment] 2021-09-23 14:40
> Hello. What version of DLE did you install the template on and how did you do it?

i have dle 14.3 after install i changed $tpl->load_template('main.tpl'); with $tpl->load_template(($_SERVER['QUERY_STRING'] == "") ? 'main.tpl' : 'pages_theme.tpl'); on here engine/modules/main.php but it didnt work

**Comment by NYCTO1337** [comment] 2021-09-23 14:41
> Hello. What version of DLE did you install the template on and how did you do it?

https://wildgeo.ga/ you can see website

**Comment by NYCTO1337** [comment] 2021-09-23 14:49
here main.php
![Untitled](https://user-images.githubusercontent.com/91264605/134529923-570d7ea2-cc48-43d3-aa63-9f776208117f.png)

**Comment by somnambul1st** [comment] 2021-09-23 14:51
Installed a clean DLE, uploaded the template and all is well. Implemented:
1. Installed clean DLE 14.3
2. Without changing anything in the settings, went into /engine/modules/main.php, replaced the line there.
3. Removed /templates/Default/ folder
4. Loaded the Default folder from freeweb-main/minecraft/dle/ into /templates/
5. Template displays and works fine.
Here's the clean install address for clarity [https://viadevelop.store/demo/nycto/](https://viadevelop.store/demo/nycto/)

**Comment by NYCTO1337** [comment] 2021-09-23 14:54
> Installed a clean DLE, uploaded the template and all is well. Implemented:
> 
> 1. Installed clean DLE 14.3
> 2. Without changing anything in the settings, went into /engine/modules/main.php, replaced the line there.
> 3. Removed /templates/Default/ folder
> 4. Loaded the Default folder from freeweb-main/minecraft/dle/ into /templates/
> 5. Template displays and works fine.
>    Here's the clean install address for clarity https://viadevelop.store/demo/nycto/

i will try one more time now

**Comment by NYCTO1337** [comment] 2021-09-23 15:02
> Installed a clean DLE, uploaded the template and all is well. Implemented:
> 
> 1. Installed clean DLE 14.3
> 2. Without changing anything in the settings, went into /engine/modules/main.php, replaced the line there.
> 3. Removed /templates/Default/ folder
> 4. Loaded the Default folder from freeweb-main/minecraft/dle/ into /templates/
> 5. Template displays and works fine.
>    Here's the clean install address for clarity https://viadevelop.store/demo/nycto/

same bug. i don't know what to do

**Comment by somnambul1st** [comment] 2021-09-23 15:05
Can you send me the link where you put it, it's just not on https://wildgeo.ga/.

**Comment by NYCTO1337** [comment] 2021-09-23 15:05
> Can you send me the link where you put it, it's just not on https://wildgeo.ga/.

there is not because i deleted dle engine and trying to upload new

**Comment by somnambul1st** [comment] 2021-09-23 15:07
OK, I see your point, waiting for an active link then

**Comment by NYCTO1337** [comment] 2021-09-23 15:10
> OK, I see your point, waiting for an active link then

https://wildgeo.ga/ it's same

**Comment by NYCTO1337** [comment] 2021-09-23 15:14
i uploading template with name "Default" but when i go on webpage control panel to change template its called Стандартный i dont know why
![Untitled](https://user-images.githubusercontent.com/91264605/134534673-bfcc3ad4-4abf-4f49-855c-98bd62c76f88.png)

**Comment by somnambul1st** [comment] 2021-09-23 15:20
Your web server is blocking the paths for some reason. As I can see from the console and from debugging sources, the template can't retrieve multiple plugins that are involved in the page design. Screenshots are attached.
![image](https://user-images.githubusercontent.com/53238089/134534823-3d041228-55f6-4a63-9f36-831852f9ecb2.png)
**That's how many there should be:**
![image](https://user-images.githubusercontent.com/53238089/134535107-500eabbe-4465-4ba6-8974-30592c1b07cb.png)
_And here are the mistakes themselves:_
![image](https://user-images.githubusercontent.com/53238089/134535200-0bc17f0f-1d0b-4283-8234-52b61fc5f8aa.png)
And when I try to access the specified file, I also get an error that I don't have enough access.
Try all the folders in plugins with 700 rights and the files in them with 600 rights. Because if I open a file from my site, it's readable from the browser: 
![image](https://user-images.githubusercontent.com/53238089/134535647-4d30a45d-91d7-43ec-a962-922db43c6f2f.png)

**Comment by NYCTO1337** [comment] 2021-09-23 15:54
> Your web server is blocking the paths for some reason. As I can see from the console and from debugging sources, the template can't retrieve multiple plugins that are involved in the page design. Screenshots are attached.
> ![image](https://user-images.githubusercontent.com/53238089/134534823-3d041228-55f6-4a63-9f36-831852f9ecb2.png)
> **That's how many there should be:**
> ![image](https://user-images.githubusercontent.com/53238089/134535107-500eabbe-4465-4ba6-8974-30592c1b07cb.png)
> _And here are the mistakes themselves:_
> ![image](https://user-images.githubusercontent.com/53238089/134535200-0bc17f0f-1d0b-4283-8234-52b61fc5f8aa.png)
> And when I try to access the specified file, I also get an error that I don't have enough access.
> Try all the folders in plugins with 700 rights and the files in them with 600 rights. Because if I open a file from my site, it's readable from the browser:
> ![image](https://user-images.githubusercontent.com/53238089/134535647-4d30a45d-91d7-43ec-a962-922db43c6f2f.png)

thank you so much. i don't know how to give rights but i will google it <3 thx

**Comment by somnambul1st** [comment] 2021-09-23 15:59
OK, I won't close the issue. If there is anything you need to write to me.

**Comment by NYCTO1337** [comment] 2021-09-23 16:00
https://wordpress.org/support/article/changing-file-permissions/ you mean this ?

**Comment by somnambul1st** [comment] 2021-09-23 16:03
Yes, you need this part https://wordpress.org/support/article/changing-file-permissions/#using-an-ftp-client

**Comment by NYCTO1337** [comment] 2021-09-23 16:05
> Yes, you need this part https://wordpress.org/support/article/changing-file-permissions/#using-an-ftp-client
i did it all plugin folders to 700 and plugin files 600.
![700](https://user-images.githubusercontent.com/91264605/134543325-d60bd970-fad8-47a0-895b-cee288414e12.png)

**Comment by somnambul1st** [comment] 2021-09-23 16:12
So. He began to see folders, try on .css and .js files in the /plugins/ folder put 644 rights.

**Comment by NYCTO1337** [comment] 2021-09-23 16:15
> So. He began to see folders, try on .css and .js files in the /plugins/ folder put 644 rights.

okay i did it too

**Comment by somnambul1st** [comment] 2021-09-23 16:21
If the problem persists, try writing to your web-hosting support, they should be able to fix the problem, as the problem is on your web-server.

**Comment by NYCTO1337** [comment] 2021-09-23 16:30
> If the problem persists, try writing to your web-hosting support, they should be able to fix the problem, as the problem is on your web-server.

And what to ask the operator?

**Comment by somnambul1st** [comment] 2021-09-23 16:34
Ask:
Installed the DLE core, then installed this template https://github.com/viadevelop/freeweb/tree/main-english . It's not displaying correctly. The developer said that the problem is with the access to the files on the server, namely the .css and .js files. Can you set the permissions so that these problems disappear.
The problem is with the files at the addresses:
/templates/Default/css/*
/templates/Default/js/*
/templates/Default/plugins/*

**Comment by NYCTO1337** [comment] 2021-09-23 19:00
Hello, me again. can this problem casued by the PHP version?

**Comment by somnambul1st** [comment] 2021-09-23 19:29
> Hello, me again. can this problem casued by the PHP version?

Maybe. What version do you have? 
P.S - My domains have 7.4

**Comment by NYCTO1337** [comment] 2021-09-23 22:21
> Maybe. What version do you have?
> P.S - My domains have 7.4
 hosting provider: The company "Proserv.ge" is constantly taking care of improving the quality of customer service and offers you to use the PHP version you want on our server. You have the option to choose PHP version 5.2 to 7.0. To make changes, go to the Hosting Control Panel and find the "Software / Services" section.

**Comment by NYCTO1337** [comment] 2021-09-23 22:52
> > Hello, me again. can this problem casued by the PHP version?
> 
> Maybe. What version do you have?
> P.S - My domains have 7.4

![Uploading Untitled.png…]()

**Comment by NYCTO1337** [comment] 2021-09-23 22:52
> > Hello, me again. can this problem casued by the PHP version?
> 
> Maybe. What version do you have?
> P.S - My domains have 7.4

![Untitled](https://user-images.githubusercontent.com/91264605/134594179-4879f152-f35e-49ad-a540-7be2aec048d5.png)

**Comment by NYCTO1337** [comment] 2021-09-23 22:54
> > Hello, me again. can this problem casued by the PHP version?
> 
> Maybe. What version do you have?
> P.S - My domains have 7.4

i tryed all version but all worse. nothing fixed 😄

**Comment by NYCTO1337** [comment] 2021-09-23 22:59
![Untitled](https://user-images.githubusercontent.com/91264605/134594688-1201c2ec-6ad7-4577-8577-97c36e363b53.png)
new error?

**Comment by somnambul1st** [comment] 2021-09-24 05:09
These were the errors, he writes that there is no actual error, i.e. all rights are correct, but no access to the files anyway. The problem is on your hosting side.

**Comment by NYCTO1337** [comment] 2021-09-24 09:38
provider says "we dont block javascripts"

**Comment by NYCTO1337** [comment] 2021-09-24 09:41
At least I will have to find another template 😄

**Comment by somnambul1st** [comment] 2021-09-24 09:43
Russian-speaking hosting providers and OVH do not have such a problem, I did not check the rest. Error 403 (Forbidden /Access is denied) is returned to the client by the server when access to the specified resource is restricted. Unfortunately I can't help you with anything (

**Closed as completed by somnambul1st** 2021-09-24 09:43 UTC
Labels: question, webhelp

**Comment by NYCTO1337** [comment] 2021-09-24 10:07
> Russian-speaking hosting providers and OVH do not have such a problem, I did not check the rest. Error 403 (Forbidden /Access is denied) is returned to the client by the server when access to the specified resource is restricted. Unfortunately I can't help you with anything (

Which hosting would you recommend?

**Comment by somnambul1st** [comment] 2021-09-24 10:09
> > Russian-speaking hosting providers and OVH do not have such a problem, I did not check the rest. Error 403 (Forbidden /Access is denied) is returned to the client by the server when access to the specified resource is restricted. Unfortunately I can't help you with anything (
> 
> Which hosting would you recommend?

https://www.ovh.ie/web-hosting/

**Comment by NYCTO1337** [comment] 2021-09-24 15:26
I hope you will design templates like this again in the future. good luck and thank you for info. ❤️
